
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: music_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d  # Ensures the SQL file is available to be run
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: flask run --host=0.0.0.0
    volumes:
      - .:/app
    environment:
      FLASK_APP: app.py
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
